---
title: 'Registration review: Paper from code'
author: "Stylianos Serghiou"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output:
  prettydoc::html_pretty:
    # no code_folding available
    theme: hpstr      # or: architect; https://github.com/yixuan/prettydoc
    highlight: github # or: vignette
    toc: TRUE         # no toc_float available
    df_print: kable   # obviates %>% kable; does not replace styling though
  tufte::tufte_handout: default
  pdf_document:
    highlight: tango
    df_print: kable
    latex_engine: pdflatex
    keep_tex: yes
  rmdformats::readthedown:
    highlight: kate
    df_print: kable    # obviates %>% kable; does not replace styling though
    code_folding: hide # or: show; (comment out to not give option)
  tufte::tufte_html: 
    toc: TRUE
  epuRate::epurate:
    df_print: kable
    toc: yes
  html_document:
    highlight: tango
    theme: sandstone
    df_print: kable
    toc: yes
    toc_depth: 2
    toc_float: yes
    css: "path_to_custom.css"
header-includes:
- \DeclareUnicodeCharacter{3B8}{~}
- \DeclareUnicodeCharacter{3B1}{~}
- \DeclareUnicodeCharacter{3B2}{~}
- \DeclareUnicodeCharacter{223C}{~}
- \DeclareUnicodeCharacter{2264}{~}
- \DeclareUnicodeCharacter{2265}{~}
- \DeclareUnicodeCharacter{2581}{~}
- \DeclareUnicodeCharacter{2582}{~}
- \DeclareUnicodeCharacter{2583}{~}
- \DeclareUnicodeCharacter{2585}{~}
- \DeclareUnicodeCharacter{2586}{~}
- \DeclareUnicodeCharacter{2587}{~} 
- \DeclareUnicodeCharacter{FB00}{~} 
- \usepackage{graphicx}
editor_options: 
  chunk_output_type: inline
---

<style>
p {

text-align: justify;
text-justify: interword;
padding: 0 0 0.5em 0

}
</style>

```{r setup, include=FALSE}
# Load packages
library(knitr)
library(rmdformats)
library(kableExtra)
library(ggplot2)
library(magrittr)



######### knitr

# Define chunk options
opts_chunk$set(
  echo = T,
  cache = F,  # if TRUE, no need to rerun chunks
  # cache.lazy = TRUE,  # use with big objects (>1 GB)
  cache.comments = F,  # do not rebuild if comments change
  tidy = F,  # can play with this
  warning = F, 
  message = F,
  comment = NA,
  fig.align = "center",
  fig.width = 7,
  # fig.path = "Figs/",  # export all figures to dir Figs
  linewidth = 91,
  width = 75
)


# Initiatialize hook
hook_output = knit_hooks$get("output")


# Hook to wrap output text when it exceeds 'n' using linewidth
knit_hooks$set(output = function(x, options) {
  
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    
    # wrap lines wider than 'n' 
    if (any(nchar(x) > n)) 
      x <- strwrap(x, width = n)
      x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})


# Times a chunk and prints the time it took to run it under the chunk
# To time a chunk, include in the chunk options: {r my_chunk, timeit=TRUE}
knitr::knit_hooks$set(timeit = local({
  now = NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res = difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste('Time for this code chunk:', as.character(res))
    }
  }})
)


# For more knitr options visit: https://yihui.name/knitr/options/
# and his github page: https://github.com/yihui/knitr-examples



######### kableExtra

options(knitr.kable.NA = ''  # replace NAs in tables with blank
        , digits = 3)          # round digits (doesn't work without this here!)

## Example use
# data.frame(x = c(1,2,3), y = c(4,5,6), z = c(7,8,9)) %>% 
#   kable(booktabs = T) %>% kable_styling()

# Function to simplify table styling
sable <- function(tab, escape = T, full_width = F, drop = F, font_size = 12) {
  if (drop) {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      collapse_rows(valign = "top") %>% 
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width, 
                    font_size = font_size)
  } else {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width,
                    font_size = font_size)
  }
}

## Guidelines
# No longer need to define options(knitr.table.format = "html"). It is now automatically done as soon as you load kableExtra
# No need to run kable() every time - done automatically as soon as you load kableExtra
# Loading kableExtra nullifies any styling applied by df_table: kable in the preamble - if you are content with standard formatting, DO NOT load kableExtra



#########  ggplot2

# Set up preferred theme in ggplot2
my_theme <- 
  # this and theme_minimal() are my favorite
  theme_light() +  
  theme(
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.title.x = element_text(margin = margin(t = 10)),
    axis.title.y  = element_text(margin = margin(r = 10)),
    legend.key = element_rect(colour = NA, fill = NA),  # Avoid borders
    panel.border = element_blank(), 
    text = element_text(color = "grey20"),
    title = element_text(face = "bold")
  )

# Make the above theme the default theme
original_theme <- theme_set(my_theme)

# Use ggsave to save plots after plotting - this reduces size dramatically



######### Live preview

# Preview the HTML without having to re-knit
# https://www.r-bloggers.com/create-r-markdown-reports-and-presentations-even-better-with-these-3-practical-tips/amp/

# xaringan::infinite_moon_reader()




######### Tabbed sections

# You can organize content using tabs by applying the .tabset class attribute to headers within a document. This will cause all sub-headers of the header with the .tabset attribute to appear within tabs rather than as standalone sections. For example:

## Quarterly Results {.tabset}

### By Product



######### Update package

# To update the package use:
# Replace ~/serghiouTemplates/inst/rmarkdown/templates/report/skeleton.rmd
# library(devtools); setwd("/Users/Stelios/"); install("serghiouTemplates")
```


# Setup {.tabset}

<!-- Chunk called setup_2 to avoid running it automatically -->

```{r setup_2}
# Load packages
library(cowplot)
library(lubridate)
library(magrittr)
library(readxl)
library(tidyverse)
library(vroom)

# Import data
pmcoa <- vroom("../../data/tidy_data/pmcoa.csv")
ct <- vroom("../../data/interim_data/clinicaltrials.csv")
```


***


# PMCOA

## By year since 1990

```{r}
pmcoa %>% 
  filter(year >= 1990) %>% 
  group_by(year) %>% 
  summarise(
    N = n(),
    n = sum(is_register_pred), 
    p = mean(is_register_pred)
  ) %>% 
  sable()
```


## By field

```{r}
pmcoa %>% 
  filter(is_register_pred) %>% 
  count(field, sort = T) %>%
  replace_na(list(field = "(Unclassified)")) %>% 
  mutate(N = sum(n)) %>% 
  mutate(p = scales::percent(n / N)) %>% 
  sable()
```


***

# Figure 1

## Create data

```{r}
registry_mentions <-  
  read_csv("../../data/tidy_data/registry_mentions.csv") %>% 
  full_join(select(pmcoa, pmcid_pmc, is_register_pred, year))
```


## Performance

```{r}
# Import test
registry_test <- read_xlsx("../../data/interim_data/pmcoa_registry-test.xlsx")

# Summarize test
registry_test %>% 
  count(is_true_negative, reason, sort = T) %>%
  group_by(is_true_negative) %>% 
  mutate(N = sum(n)) %>% 
  mutate(p = scales::percent(n / N, accuracy = 0.1)) %>%
  arrange(desc(is_true_negative)) %>% 
  sable()
```


## Plot

```{r}
registries <- 
  registry_mentions %>% 
  filter(is_register_pred & nchar(registries) > 0) %>% 
  separate_rows(registries, sep = "; ") %>% 
  distinct(pmcid_pmc, registries, .keep_all = T) %>% 
  count(year, registries) %>% 
  group_by(year) %>% 
  mutate(N = sum(n)) %>% 
  mutate(p = n / N) %>% 
  ungroup()
```

```{r}
# Define order
in_order <- 
  registries %>% 
  filter(year == 2019) %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  select(registries, inorder = n)

# Plot
registries %>%
  left_join(in_order) %>% 
  filter(year < 2020) %>% 
  mutate(registries = fct_reorder(registries, desc(inorder))) %>% 
  ggplot(aes(x = year, y = n, color = registries)) +
  geom_line() +
  scale_color_manual(
    breaks = c(in_order$registries[1:6]),
    values = c(scales::hue_pal()(6), rep("grey80",  nrow(in_order) - 6)),
    name = "Registry"
  ) +
  labs(x = "Year", y = "Number of studies")

# Save
ggsave(
  "../../output/figure_output/paper-from-code_figure-1.jpg",
  width = 8,
  height = 6
)
```


***


# Figure 2

## Crete data

```{r}
over_time <- 
  ct %>% 
  select(first_submitted_date, study_type) %>% 
  filter(study_type != "Expanded Access") %>% 
  mutate(across(study_type, na_if, "N/A")) %>% 
  mutate(across(study_type, str_extract, "[a-zA-Z]+")) %>% 
  mutate(first_submitted_date = as.Date(first_submitted_date, "%B %d, %Y")) %>% 
  mutate(first_submitted_year = lubridate::year(first_submitted_date)) %>% 
  count(first_submitted_year, study_type)
```


## Plot

```{r}
# Plot
over_time %>% 
  drop_na(study_type) %>% 
  filter(first_submitted_year < 2020) %>% 
  ggplot(aes(x = first_submitted_year, y = n, color = study_type)) +
  geom_line() +
  labs(x = "Year submitted", y = "Number of studies", color = NULL) +
  scale_y_continuous(labels = scales::comma)

# Save
ggsave(
  "../../output/figure_output/paper-from-code_figure-2.jpg",
  width = 8,
  height = 6
)
```


***


# Supplementary Table 1

## Create data

STROBE-inspired criteria.

```{r}
box <- 
  ct %>% 
  mutate(
    is_observational_model = !is.na(observational_model),
    is_time_perspective = !is.na(time_perspective),
    is_study_start_date = 
      !is.na(actual_study_start_date) | 
      !is.na(anticipated_study_start_date),
    is_study_completion_date = 
      !is.na(actual_primary_completion_date) |
      !is.na(anticipated_primary_completion_date),
    is_collection_dates = is_study_start_date & is_study_completion_date,
    is_study_population = !is.na(study_population),
    is_condition = !is.na(condition),
    is_eligibility_criteria = case_when(
      is.na(eligibility_criteria) ~ FALSE,
      str_detect(eligibility_criteria, "No eligibility criteria") ~ FALSE,
      str_detect(eligibility_criteria, "^Please contact site") ~ FALSE,
      TRUE ~ TRUE
    ),
    is_sampling_method = !is.na(sampling_method),
    is_primary_outcome = !is.na(primary_outcome_measure),
    is_intervention_type_arm_group = 
      !is.na(intervention_type) | 
      !is.na(arm_group_arm_group_label),
    is_study_size_target = !is.na(enrollment_target),
    is_primary_outcome_measure = !is.na(primary_outcome_measure),
    is_primary_outcome_time_frame = !is.na(primary_outcome_time_frame),
    is_primary_outcome_description = !is.na(primary_outcome_description),
    is_results = !is.na(results_first_posted_date),
    is_ipd = case_when(
      is.na(patient_data_sharing_ipd) ~ FALSE,
      patient_data_sharing_ipd %in% c("No", "Undecided") ~ FALSE,
      TRUE ~ TRUE
    ),
    is_sponsor = !is.na(study_sponsor),
    is_published = !is.na(publications_PMID)
  ) %>% 
  select(nct_id, study_type, starts_with("is_"))

# Identify large documents
large_docs <- 
  ct %>% 
  separate_rows(large_doc_type, large_doc_has_sap, sep = "; ") %>% 
  unite(col = "doc_exists", large_doc_type, large_doc_has_sap, sep = "; ") %>% 
  group_by(nct_id) %>% 
  summarise(
    is_protocol = any(str_detect(doc_exists, "Protocol.*; Yes")),
    is_sap = any(str_detect(doc_exists, "Statistical.*; Yes"))
  ) %>%
  ungroup()

# Combine
box %<>% full_join(large_docs)
```


## Tabulate

```{r}
# Tabulate
box <- 
  box %>% 
  filter(!study_type %in% c("Expanded Access", "N/A")) %>% 
  mutate(across(study_type, str_extract, "[a-zA-Z]+")) %>% 
  gather(key, value, starts_with("is_")) %>% 
  mutate(key = fct_inorder(key)) %>% 
  group_by(study_type, key) %>%
  summarise(
    n = scales::comma(sum(value)), 
    prop = scales::percent(mean(value), accuracy = 0.1)
  ) %>% 
  ungroup() %>% 
  mutate(value = glue::glue("{n} ({prop})")) %>% 
  pivot_wider(id_col = key, names_from = study_type, values_from = value) 

# Print
box %>% sable()

# Save
write_csv(box, "../../output/table_output/paper-from-code_box-1.csv")
```


***


# Supplementary figure 1

## Create data

```{r}
pubmed <- read_csv("../../data/interim_data/pubmed.csv")
```


## Plot

```{r}
pubmed %>% 
  mutate(
    registers = fct_reorder(registers, -counts),
    n = scales::comma(counts),
    p = scales::percent(counts / sum(counts)),
    n_p = glue::glue("{n} ({p})")
  ) %>% 
  ggplot(aes(x = registers, y = counts, fill = registers, color = registers)) +
  geom_col(alpha = 0.75, show.legend = F) +
  geom_text(
    aes(label = n_p), 
    size = 3, 
    vjust = -0.5, 
    show.legend = F
  ) +
  labs(x = NULL, y = "Number of titles or abstracts") +
  scale_y_continuous(labels = scales::comma) +
  theme(
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(margin = margin(t = -5))
  )

# Save
ggsave(
  "../../output/figure_output/paper-from-code_supplementary-figure-2.jpg",
  width = 8,
  height = 6
)
```


***


# Documentation {.tabset}

## Session Info

```{r session_info, echo=FALSE}
print(sessionInfo(), locale = F)
```


## References

```{r refs, echo=FALSE}
(.packages()) %>% sort %>% lapply(citation) %>% lapply(c) %>% unique
```
